<a href="https://colab.research.google.com/github/hanene2030/pandas/blob/main/10_pandas_styling_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas styling data

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.normal(size=(6,6)), columns=[x for x in "ABCDEF"] )
df

          A         B         C         D         E         F
0 -1.034158 -0.435203 -1.379853 -0.504631 -0.557008  0.573372
1 -0.359500 -0.016423 -0.636219 -0.386231 -0.807955 -0.465529
2  0.095850  1.475509 -0.447418  2.917481 -0.306232 -0.745321
3 -1.126141 -2.184647 -0.155073  0.948026 -1.085388  0.367227
4 -1.695002 -0.781230  1.533258  0.676114  0.931985 -0.552185
5  2.578448  0.134210  0.983896  0.355770 -1.783074 -0.509740

In [7]:
#Show all negative numbers in red
def neg_red(x):
  return f"color:{'red' if x < 0 else 'green'}"
df.style.applymap(neg_red)

In [10]:
def gold_max(xs):
  m = xs.to_numpy().max()
  color ={True: "background-color: yellow",False: ""}
  is_max = (xs == m).replace(color)
  return is_max
df.style.apply(gold_max, axis=1) # row by row

In [12]:
df.style.background_gradient(cmap="magma")

In [18]:
df.abs().style.bar(align="left", width=95)

In [20]:
df.abs().style.highlight_min(["A","B"], color="red")

In [23]:
df.abs().style.highlight_between(color='blue', axis=None, left=1, right=2, inclusive='both')

In [30]:
df.style.text_gradient(cmap='inferno') # Matplotlib colormap

In [32]:
head = [{"selector": "th", "props": [("text-align", "center")]}]
df.style.set_table_styles(head).bar(align='mid', color=["blue", "green"], vmin=3, vmax=3)

In [33]:
# we can chain them all together
df.style.bar(align="mid", width=50).apply(gold_max, axis=None).applymap(neg_red)

In [ ]:
df.style.text_gradient(cmap='PuBu')